name: Diya Studio
favicon: null
layout_spectrum: 0.37007000111043453
typography_spectrum: 0.08888482372276485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2521295053884387
  lightness: 0.03130433242768049
  saturation: 0.9380331744905561
  rhythmicContrast: 0.42623408138751984
purpose: []
